### ISSUE TITLE
Status of MCMCBenchmarks

### ISSUE THREAD

**Issue by goedman** [StatisticalRethinkingJulia/MCMCBenchmarks.jl#23]
Hi Chris,

The results (your results as stored in the repo) look great and are very useful. This is not a package that folks will be `using` to build other packages, but more intended to take snapshots and look for improvements and regressions. Or someone could create a PR to add another example. 

I've been trying to get a bit further with MCMCBenchmarks (on the rjg/osx branch). My hope was to get a relative short example (maybe a derivative of Gaussian?) running and move that over to runtests.jl and be of help with documenting the structure of the examples and the results.

My problem is that none of the examples work anymore (even the Gaussian example stopped working). Gradient errors, pyplot issues, parsing Manifest.toml (or simply finding the file) are some of the things I have noticed. After a reinstall of all of Julia, Revise works a bit better (but still occasionally produces pages of errors) and PyPlot is working again. That might help. I sometimes remove Turing (AMHCNUTS) from the examples as it simply takes too long for testing. 

Clearly, I'm struggling on how to proceed and help.

Rob

**Comment by itsdfish** [comment]
Hi Rob-

Wow. That doesn't sound good. Let me start by seeing if things run on my system and report back.

**Comment by itsdfish** [comment]
Hey Rob. I was able to run the Gaussian Example without it crashing. I was wondering if you could provide a bit more detail regarding the issues you are having, specially with the Gaussian model since that is working well on my system. Also, could you tell me the location of you Manifest.toml file and where the package attempts to look? Here are issues I am aware of:

1. The pyplot backend seems to be temperamental. Changing to the GR backend might be the simplest solution if that still works on your system. 

2. Turing produces lots of gradient errors, particularly for the LBA and and Hierarchical Poisson. I recently reported those issues to Turing. Are you experiencing errors with other samplers or models?

3. Turing is very slow. Hopefully that will be resolved in future releases. Depending on your goals, there are a few workarounds that could be used in the meantime. One solution is to exclude Turing and compare DynamicHMC and CmdStan. Another solution might be to explore HMC samples in Turing. Kai [noted](https://github.com/TuringLang/Turing.jl/issues/840#issuecomment-508935191) that it performs better in terms of effective sample size. It might work better in terms of speed too. I'm not sure. 

4. The Gaussian model seems to work mostly ok on my system, but will throw an occasional warning message. For example CmdStan throws the following warning 56 times out of 150 runs:

 Informational Message: The current Metropolis proposal is about to be rejected because of the following issue:
`      From worker 5:    Exception: normal_lpdf: Scale parameter is 0, but must be > 0!  (in '/home/dfish/.julia/dev/MCMCBenchmarks/Examples/Gaussian/tmp/CmdStanGaussian5.stan' at line 12)`

The parameter sigma is constrained to have a lower bound of zero:  `real<lower=0> sigma;`.So this value is certainly allowable in terms of the lower bound. It appeared to happen more often with higher sample sizes. Although the warning appears fairly often, the parameters appear to be recovered correctly and according to visual inspection, are comparable to the other samplers. So it does not seem to be a problem, but I could possible perform a more formal analysis. 

 In 13 out of 150 runs of the model, I found the following error:

```
┌ Warning: Numerical error in gradients. Rejecting current proposal...
└ @ Turing.Core ~/.julia/packages/Turing/RZOZ8/src/core/ad.jl:169
┌ Warning: grad = Real[437.852, NaN]
└ @ Turing.Core ~/.julia/packages/Turing/RZOZ8/src/core/ad.jl:170
```

Are you experiencing these errors/warnings at a higher rate and do you think they are problematic?

**Comment by goedman** [comment]
Thanks Chris. Can I run this with far fewer nreps, like nrep=20? The Manifest issue I think was due to me running it at Julia 1.3-DEV. I now switched back to 1.1.1 and just started it again.

**Comment by itsdfish** [comment]
Yeah. I think that is a good idea.

**Comment by goedman** [comment]
Aah, 1.1.1 behaves way better!!!!! With nrep=20 Gaussian completes:
```
<... snipped everything above>

      From worker 3:	Pair{Symbol,Real}(:Nadapt, 1000)
      From worker 3:	Pair{Symbol,Real}(:delta, 0.8)
      From worker 3:	Pair{Symbol,Real}(:Nd, 1000)
[ Info: Precompiling PyPlot [d330b81b-6aea-500a-939a-2ce795aea3ee]
[ Info: Installing matplotlib via the Conda matplotlib package...
[ Info: Running `conda install -y matplotlib` in root environment
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/rob/.julia/conda/3

  added / updated specs:
    - matplotlib


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cycler-0.10.0              |           py37_0          14 KB
    freetype-2.9.1             |       hb4e5f40_0         555 KB
    kiwisolver-1.1.0           |   py37h0a44026_0          54 KB
    libpng-1.6.37              |       ha441bb4_0         262 KB
    matplotlib-3.1.0           |   py37h54f8f79_0         4.9 MB
    pyparsing-2.4.0            |             py_0          58 KB
    python-dateutil-2.8.0      |           py37_0         265 KB
    pytz-2019.1                |             py_0         236 KB
    tornado-6.0.3              |   py37h1de35cc_0         644 KB
    ------------------------------------------------------------
                                           Total:         6.9 MB

The following NEW packages will be INSTALLED:

  cycler             pkgs/main/osx-64::cycler-0.10.0-py37_0
  freetype           pkgs/main/osx-64::freetype-2.9.1-hb4e5f40_0
  kiwisolver         pkgs/main/osx-64::kiwisolver-1.1.0-py37h0a44026_0
  libpng             pkgs/main/osx-64::libpng-1.6.37-ha441bb4_0
  matplotlib         pkgs/main/osx-64::matplotlib-3.1.0-py37h54f8f79_0
  pyparsing          pkgs/main/noarch::pyparsing-2.4.0-py_0
  python-dateutil    pkgs/main/osx-64::python-dateutil-2.8.0-py37_0
  pytz               pkgs/main/noarch::pytz-2019.1-py_0
  tornado            pkgs/main/osx-64::tornado-6.0.3-py37h1de35cc_0



Downloading and Extracting Packages
tornado-6.0.3        | 644 KB    | ###################################################################### | 100% 
python-dateutil-2.8. | 265 KB    | ###################################################################### | 100% 
pyparsing-2.4.0      | 58 KB     | ###################################################################### | 100% 
freetype-2.9.1       | 555 KB    | ###################################################################### | 100% 
cycler-0.10.0        | 14 KB     | ###################################################################### | 100% 
kiwisolver-1.1.0     | 54 KB     | ###################################################################### | 100% 
libpng-1.6.37        | 262 KB    | ###################################################################### | 100% 
matplotlib-3.1.0     | 4.9 MB    | ###################################################################### | 100% 
pytz-2019.1          | 236 KB    | ###################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
4-element Array{Plots.Plot,1}:
 Plot{Plots.PyPlotBackend() n=9}
 Plot{Plots.PyPlotBackend() n=9}
 Plot{Plots.PyPlotBackend() n=9}
 Plot{Plots.PyPlotBackend() n=9}
```

So the problem must have been trying to run on 1.3-DEV and that is a problem for down the road!

Indeed I do see a limited number of the informational Stan messages, but basically very few.

I see 900 rows in results.csv, 300/sampler, 15/(sampler/repetition), 5/(sampler/repetition/Nd)?

This is cool. You've done a really nice job in the plots!

**Comment by itsdfish** [comment]
Excellent! I'm glad it works on 1.1.1 What you have described seems to be correct. 

Thanks. The plots were tricky, but I am fairly happy with the flexibility and coverage provided by the three functions. Note that you can also overwrite defaults, such as axis labels, with optional keyword arguments.

**Comment by goedman** [comment]
How do you want to preserve the graphical results? One option could be a minor release that contains one set of graphs for each sampler. We can’t use Literate.jl as in StatisticalRethinking because we would exceed our time limit. We could use Documenter.jl and move one set of plots to the docs subdirectory just before we do a minor release. 

Or do you think we don’t need such a trail and stick with something like the current README? Nice job by the way!

I wonder if we should allocate the results directory using mktempdir() or in some user definable place? That way the repo doesn’t become dirty.

**Comment by itsdfish** [comment]
Good question. It might be nice to integrate a results section into the documentation. If there are storage constraints, we could try to focus on key findings. For example, we could focus on the Gaussian model if the patterns are consistent across different models. Documenter.jl looks like it might work, but I'm open to other suggestions. 

I think your idea about outputting figures to a user defined directory is a good idea. The current setup works good for development, but would make the repo dirty as you noted. I'll open an issue for that.
